import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "TURISMO INTELIGENTE",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="navbar">
          <nav className="menu-bar">
            <ul className="menu">
              <li>
                <Link href="/">Inicio</Link>
              </li>
              <li>
                <Link href="/contacto">Contacto</Link>
              </li>
              <li>
                <Link href="/recomendaciones">Recomendaciones</Link>
              </li>
              <li>
                <Link href="/rutas">Generacion rutas</Link>
              </li>
            </ul>
          </nav>
        </header>
        <main>{children}</main>
        <footer className="back-button">
          <Link href="/">← Regresar</Link>
        </footer>
      </body>
    </html>
  );
}
